import * as THREE from "three";

// Face Geometry Constants
export const FACE_GEOMETRY = {
  TUBE_RADIUS: 0.02,

  // Forehead vertices
  FOREHEAD_TOP_CENTER: new THREE.Vector3(0, 0.8, 0),
  FOREHEAD_TOP_RIGHT: new THREE.Vector3(0.4, 0.7, 0),
  FOREHEAD_RIGHT_TEMPLE: new THREE.Vector3(0.6, 0.5, 0),
  FOREHEAD_RIGHT_SIDE: new THREE.Vector3(0.7, 0.3, 0),
  FOREHEAD_TOP_LEFT: new THREE.Vector3(-0.4, 0.7, 0),
  FOREHEAD_LEFT_TEMPLE: new THREE.Vector3(-0.6, 0.5, 0),
  FOREHEAD_LEFT_SIDE: new THREE.Vector3(-0.7, 0.3, 0),

  // Eye vertices
  RIGHT_EYE_OUTER: new THREE.Vector3(0.3, 0.2, 0.1),
  RIGHT_EYE_INNER: new THREE.Vector3(0.1, 0.2, 0.1),
  RIGHT_EYE_LOWER_INNER: new THREE.Vector3(0.1, 0.1, 0.1),
  RIGHT_EYE_LOWER_OUTER: new THREE.Vector3(0.3, 0.1, 0.1),
  LEFT_EYE_OUTER: new THREE.Vector3(-0.3, 0.2, 0.1),
  LEFT_EYE_INNER: new THREE.Vector3(-0.1, 0.2, 0.1),
  LEFT_EYE_LOWER_INNER: new THREE.Vector3(-0.1, 0.1, 0.1),
  LEFT_EYE_LOWER_OUTER: new THREE.Vector3(-0.3, 0.1, 0.1),

  // Nose vertices
  NOSE_TIP: new THREE.Vector3(0, 0, 0.2),
  NOSE_BRIDGE: new THREE.Vector3(0, 0.3, 0.1),
  RIGHT_NOSTRIL: new THREE.Vector3(0.1, 0.1, 0.1),
  LEFT_NOSTRIL: new THREE.Vector3(-0.1, 0.1, 0.1),

  // Mouth vertices
  RIGHT_MOUTH_CORNER: new THREE.Vector3(0.2, -0.2, 0.1),
  RIGHT_MOUTH_LOWER: new THREE.Vector3(0.1, -0.3, 0.1),
  MOUTH_CENTER_LOWER: new THREE.Vector3(0, -0.4, 0.1),
  RIGHT_MOUTH_UPPER: new THREE.Vector3(0.1, -0.2, 0.1),
  LEFT_MOUTH_CORNER: new THREE.Vector3(-0.2, -0.2, 0.1),
  LEFT_MOUTH_LOWER: new THREE.Vector3(-0.1, -0.3, 0.1),
  LEFT_MOUTH_UPPER: new THREE.Vector3(-0.1, -0.2, 0.1),

  // Chin and jaw vertices
  RIGHT_CHIN: new THREE.Vector3(0.2, -0.5, 0),
  RIGHT_JAW_UPPER: new THREE.Vector3(0.4, -0.4, 0),
  RIGHT_JAW_MIDDLE: new THREE.Vector3(0.5, -0.2, 0),
  RIGHT_CHEEK: new THREE.Vector3(0.6, -0.1, 0),
  LEFT_CHIN: new THREE.Vector3(-0.2, -0.5, 0),
  LEFT_JAW_UPPER: new THREE.Vector3(-0.4, -0.4, 0),
  LEFT_JAW_MIDDLE: new THREE.Vector3(-0.5, -0.2, 0),
  LEFT_CHEEK: new THREE.Vector3(-0.6, -0.1, 0),

  // Cheek vertices
  RIGHT_CHEEK_UPPER: new THREE.Vector3(0.7, 0.1, 0),
  RIGHT_CHEEK_MIDDLE: new THREE.Vector3(0.7, 0, 0),
  RIGHT_CHEEK_LOWER: new THREE.Vector3(0.7, -0.1, 0),
  LEFT_CHEEK_UPPER: new THREE.Vector3(-0.7, 0.1, 0),
  LEFT_CHEEK_MIDDLE: new THREE.Vector3(-0.7, 0, 0),
  LEFT_CHEEK_LOWER: new THREE.Vector3(-0.7, -0.1, 0),
} as const;

// Face Edge Connections
export const FACE_EDGES: Array<[THREE.Vector3, THREE.Vector3]> = [
  // Forehead outline
  [FACE_GEOMETRY.FOREHEAD_TOP_CENTER, FACE_GEOMETRY.FOREHEAD_TOP_RIGHT],
  [FACE_GEOMETRY.FOREHEAD_TOP_RIGHT, FACE_GEOMETRY.FOREHEAD_RIGHT_TEMPLE],
  [FACE_GEOMETRY.FOREHEAD_RIGHT_TEMPLE, FACE_GEOMETRY.FOREHEAD_RIGHT_SIDE],
  [FACE_GEOMETRY.FOREHEAD_TOP_CENTER, FACE_GEOMETRY.FOREHEAD_TOP_LEFT],
  [FACE_GEOMETRY.FOREHEAD_TOP_LEFT, FACE_GEOMETRY.FOREHEAD_LEFT_TEMPLE],
  [FACE_GEOMETRY.FOREHEAD_LEFT_TEMPLE, FACE_GEOMETRY.FOREHEAD_LEFT_SIDE],

  // Eye outlines - right
  [FACE_GEOMETRY.RIGHT_EYE_OUTER, FACE_GEOMETRY.RIGHT_EYE_INNER],
  [FACE_GEOMETRY.RIGHT_EYE_INNER, FACE_GEOMETRY.RIGHT_EYE_LOWER_INNER],
  [FACE_GEOMETRY.RIGHT_EYE_LOWER_INNER, FACE_GEOMETRY.RIGHT_EYE_LOWER_OUTER],
  [FACE_GEOMETRY.RIGHT_EYE_LOWER_OUTER, FACE_GEOMETRY.RIGHT_EYE_OUTER],

  // Eye outlines - left
  [FACE_GEOMETRY.LEFT_EYE_OUTER, FACE_GEOMETRY.LEFT_EYE_INNER],
  [FACE_GEOMETRY.LEFT_EYE_INNER, FACE_GEOMETRY.LEFT_EYE_LOWER_INNER],
  [FACE_GEOMETRY.LEFT_EYE_LOWER_INNER, FACE_GEOMETRY.LEFT_EYE_LOWER_OUTER],
  [FACE_GEOMETRY.LEFT_EYE_LOWER_OUTER, FACE_GEOMETRY.LEFT_EYE_OUTER],

  // Nose
  [FACE_GEOMETRY.NOSE_BRIDGE, FACE_GEOMETRY.NOSE_TIP],
  [FACE_GEOMETRY.NOSE_TIP, FACE_GEOMETRY.RIGHT_NOSTRIL],
  [FACE_GEOMETRY.NOSE_TIP, FACE_GEOMETRY.LEFT_NOSTRIL],

  // Mouth outline
  [FACE_GEOMETRY.RIGHT_MOUTH_CORNER, FACE_GEOMETRY.RIGHT_MOUTH_LOWER],
  [FACE_GEOMETRY.RIGHT_MOUTH_LOWER, FACE_GEOMETRY.MOUTH_CENTER_LOWER],
  [FACE_GEOMETRY.MOUTH_CENTER_LOWER, FACE_GEOMETRY.LEFT_MOUTH_LOWER],
  [FACE_GEOMETRY.LEFT_MOUTH_LOWER, FACE_GEOMETRY.LEFT_MOUTH_CORNER],
  [FACE_GEOMETRY.LEFT_MOUTH_CORNER, FACE_GEOMETRY.LEFT_MOUTH_UPPER],
  [FACE_GEOMETRY.LEFT_MOUTH_UPPER, FACE_GEOMETRY.RIGHT_MOUTH_UPPER],
  [FACE_GEOMETRY.RIGHT_MOUTH_UPPER, FACE_GEOMETRY.RIGHT_MOUTH_CORNER],

  // Chin and jaw - right
  [FACE_GEOMETRY.RIGHT_CHIN, FACE_GEOMETRY.RIGHT_JAW_UPPER],
  [FACE_GEOMETRY.RIGHT_JAW_UPPER, FACE_GEOMETRY.RIGHT_JAW_MIDDLE],
  [FACE_GEOMETRY.RIGHT_JAW_MIDDLE, FACE_GEOMETRY.RIGHT_CHEEK],

  // Chin and jaw - left
  [FACE_GEOMETRY.LEFT_CHIN, FACE_GEOMETRY.LEFT_JAW_UPPER],
  [FACE_GEOMETRY.LEFT_JAW_UPPER, FACE_GEOMETRY.LEFT_JAW_MIDDLE],
  [FACE_GEOMETRY.LEFT_JAW_MIDDLE, FACE_GEOMETRY.LEFT_CHEEK],

  // Cheeks - right
  [FACE_GEOMETRY.RIGHT_CHEEK_UPPER, FACE_GEOMETRY.RIGHT_CHEEK_MIDDLE],
  [FACE_GEOMETRY.RIGHT_CHEEK_MIDDLE, FACE_GEOMETRY.RIGHT_CHEEK_LOWER],

  // Cheeks - left
  [FACE_GEOMETRY.LEFT_CHEEK_UPPER, FACE_GEOMETRY.LEFT_CHEEK_MIDDLE],
  [FACE_GEOMETRY.LEFT_CHEEK_MIDDLE, FACE_GEOMETRY.LEFT_CHEEK_LOWER],

  // Connect forehead to eyes
  [FACE_GEOMETRY.FOREHEAD_TOP_RIGHT, FACE_GEOMETRY.RIGHT_EYE_OUTER],
  [FACE_GEOMETRY.FOREHEAD_TOP_LEFT, FACE_GEOMETRY.LEFT_EYE_OUTER],

  // Connect eyes to nose
  [FACE_GEOMETRY.RIGHT_EYE_INNER, FACE_GEOMETRY.NOSE_BRIDGE],
  [FACE_GEOMETRY.LEFT_EYE_INNER, FACE_GEOMETRY.NOSE_BRIDGE],

  // Connect nose to mouth
  [FACE_GEOMETRY.NOSE_TIP, FACE_GEOMETRY.RIGHT_MOUTH_UPPER],
  [FACE_GEOMETRY.NOSE_TIP, FACE_GEOMETRY.LEFT_MOUTH_UPPER],

  // Connect mouth to chin
  [FACE_GEOMETRY.RIGHT_MOUTH_CORNER, FACE_GEOMETRY.RIGHT_CHIN],
  [FACE_GEOMETRY.LEFT_MOUTH_CORNER, FACE_GEOMETRY.LEFT_CHIN],

  // Connect jaw to cheeks
  [FACE_GEOMETRY.RIGHT_CHEEK, FACE_GEOMETRY.RIGHT_CHEEK_LOWER],
  [FACE_GEOMETRY.LEFT_CHEEK, FACE_GEOMETRY.LEFT_CHEEK_LOWER],

  // Connect cheeks to temples
  [FACE_GEOMETRY.RIGHT_CHEEK_UPPER, FACE_GEOMETRY.FOREHEAD_RIGHT_TEMPLE],
  [FACE_GEOMETRY.LEFT_CHEEK_UPPER, FACE_GEOMETRY.FOREHEAD_LEFT_TEMPLE],
];

// Colors and Materials
export const COLORS = {
  BACKGROUND: 0x0a0a0a,
  FACE_WIREFRAME: 0x4a9eff,
  FACE_EMISSIVE: 0x1e3a8a,
} as const;

// Material Properties
export const MATERIAL_PROPERTIES = {
  METALNESS: 0.8,
  ROUGHNESS: 0.2,
  EMISSIVE_INTENSITY: 0.3,
} as const;
